import LocalizedStrings from 'react-native-localization';

export default new LocalizedStrings({
  en: {
    //English
    LangID: '1',
    Tiler: 'Tiler',
    Painter: 'Painter',
    User: 'User',
    DiscoverBestSelling: 'Discover Our \nBest - Selling',
    VirtualRoom: 'Virtual Room',
    PaintOnline: 'Paint your room online using our virtual room technology',
    TechnicalExcellence: 'Technical Excellence',
    TakeTour: 'Take tour',
    OurProducts: 'Our Products',
    AllProducts: 'Show more',
    Filter: 'Filter',
    Home: 'Home',
    Products: 'Products',
    MyOrders: 'My Orders',
    MyWishList: 'My Wishlist',
    Gallery: 'Gallery',
    Videos: 'Videos',
    Articles: 'Articles',
    Offers: 'Offers',
    ContactUS: 'Contact Us',
    Login: 'Login',
    Logout: 'Logout',
    SalesTerms: 'Sales Terms',
    TermsNConditions: 'Terms and Conditions',
    PrivacyPolicy: 'Privacy Policy',
    FindColor: 'Find your product',
    ProdectsOffers: 'Products with special offers',
    ATOZ: 'A-Z',
    ZTOA: 'Z-A',
    Color: 'Color',
    LowToHigh: 'Lowest to Highest',
    HighToLow: 'Highest to Lowest',
    Price: 'Price',
    Date: 'Date',
    Place: 'Place',
    Keywords: 'Keywords',
    SearchPlaceholder: 'Ex. matt',
    TDS: 'TDS',
    MSDS: 'MSDS',
    Certificate: 'Certificate',
    AddToCart: 'Add to Cart',
    AddToWishlist: 'Add to Wishlist',
    RemoveWishlist: 'Remove wishlist',
    PaintCalculator: 'Material Calculation',
    PaintCalculatorTitle: 'Material Calculation',
    BookCall: 'Book a Call',
    RequestAgent: 'Request an Agent',
    RelatedItems: 'Related items',
    Download: 'Download',
    PickDateTime: 'Pick Date & Time',
    Time: 'Time',
    Submit: 'Submit',
    Email: 'Email',
    Password: 'Password',
    Failed: 'Failed',
    Success: 'Success',
    OR: 'Or',
    ForgotPass: 'Forgot Password ?',
    CreateAccount: 'Create a new Account ?',
    EnterEmailToSendCode: 'Enter  your Email/Phone to send you a new password',
    EnterEmail: 'Email feild is required!',
    EnterPassword: 'Password feild is required!',
    EnterValidEmail: 'Enter a valid Email!',
    PasswordTooShort: 'Password is too Short!',
    EmailPassIncorrect:
      'Email or password is incorrect! check your credintials and try again',
    UserLoggedIn: 'User logged in successfully!',
    Register: 'Register',
    HaveAccount: 'Have an account? Login',
    Fullname: 'Full Name',
    Phone: 'Phone',
    ConfirmPassword: 'Confirm Password',
    AgreeStatements: 'I agree all statements in ',
    TermsOfService: 'Terms of Service!',
    TermsOfSales: 'Terms of Sales!',
    EnterFullName: 'Full Name feild is required!',
    FullnameTooShort: 'Full Name is too short!',
    EnterPhone: 'Phone feild is required!',
    PhoneTooShort: 'Phone is too short!',
    PassDontMatch: "Password doesn't match!",
    EnterConfirmPassword: 'Confirm password feild is required!',
    EmailAlreadyTaken:
      'Sorry! there is already an account using this email. try to login or use another email.',
    UserRegisterdSucessfully: 'User registered successfully!',
    Required: 'Required',
    UserAgreeRequired:
      'You have to agree to our Terms of Service and Terms of Sales in order to use our services.',
    LearnMore: 'Learn more',
    Item: 'Item',
    Delete: 'Delete',
    WishList: 'Wishlist',
    VideoGallery: 'Video\nGallery',
    SwitchToPhoto: 'Switch To Photo Gallery',
    Veiws: 'Veiws',
    PhotoGallery: 'Photo Gallery',
    SwitchToVideo: 'Switch To Video Gallery',
    Blog: 'Blog',
    LearnAboutPaint: 'Learn about your favorite paint',
    YourCart: 'Your Cart',
    Checkout: 'Checkout',
    TrackYOrder: 'Track your order',
    JOD: 'JOD',
    ContinueShopping: 'Continue shopping',
    ContactInfo: 'Contact information',
    ShippingAddress: 'Shipping address',
    FirstName: 'First name',
    LastName: 'Last name',
    Address: 'Address',
    Apartment: 'Apartment, suite, etc.',
    OrderPlaced: 'Order Placed successfully',
    ProcessOrder: 'Processing order',
    ShippingOrder: 'Shipping order',
    OrderDelivered: 'Order Delivered',
    HappyToHelp: "We're happy to answer questions or help you with returns",
    DistrebutionPoints: 'Distribution points',
    ClickLocation: 'Click on the location to view',
    VisitFactory: 'Visit the factory',
    MyProfile: 'My Profile',
    Hello: 'Hello',
    EditProfile: 'Edit Profile',
    MyInfo: 'My Info',
    MyPassword: 'My Password',
    MyAddresses: 'My Addresses',
    Sale: '%  Sale',
    Question: 'Q',
    Next: 'Next',
    Back: 'Back',
    PinYourLocation: 'Pin your location ...',
    ProfileUpdatedSuccess: 'Profile updated successfully!',
    TakeSurvey: 'Take a survey',
    EditPassword: 'Edit password',
    PasswordChangedSuccess: 'Password changed successfully!',
    OrderNo: 'Order no.',
    OrderDate: 'Order date',
    Total: 'Total',
    MoreDetails: 'More details',
    AddNewAddress: 'Add new Address',
    AddressName: 'Address name',
    AddressNameTooShort: 'Address name is too short',
    Notifications: 'Notifications',
    UseCamera: 'Camera',
    UseGallery: 'Gallery',
    Quantity: 'Quantity',
    HowMuchPaint: 'How much paint do I need ?',
    NoNeedCrunch:
      'No need to crunch numbers. Our handy paint calculator started, enter the dimensions of the surface(s) you’re painting (in meter).\nOur paint estimator assumes a two-coat application for optimal coverage',
    EnterDimensions: 'Enter the dimensions of each surface area',
    CustomFeild: 'Custom field values',
    Area: 'Area',
    Width: 'Width',
    Height: 'Height',
    AddWall: 'Add Wall',
    SubtractWindowsDoors: 'Subtract windows & doors from calculation',
    Window: 'Window',
    Door: 'Door',
    HowMuchNeeded: 'How much you need for {0} m2',
    HowMuch2Coats: 'How Much You Need For 2 Coats',
    Paint: 'Paint',
    Galons: 'Galons',
    Primer: 'Primer',
    UserExists: 'User with these information already exists!',
    Oops: 'Oops! something went wrong, please try again.',
    NotSupported: 'Your device does not support open maps!',
    WhatsappNotSupported: 'Your device does not have Whatsapp',
    PhoneIsUsed: 'This phone is used!',
    RemovedSuccessfully: 'Item removed successfully!',
    AddedSuccessfully: 'Item added successfully!',
    SelectDay: 'Select call preferred day in order to continue!',
    SelectTime: 'Select call preferred time in order to continue!',
    BookedSuccesfully:
      'Call booked successfully! our team will contact you on time.',
    OnlyAvailableStock: 'You cant add more than {0} for now.',
    CheckCode: 'Check code',
    IncorrectCode: 'Incorrect code!',
    EnterCode: 'Enter code to continue!',
    TypeHere: 'Type here ...',
    YourCartIsEmpty: 'Your cart is empty',
    Size: 'Size',
    ShouldSelectColor: 'You should select one of the colors to continue!',
    ShouldSelectSize: 'You should select one of the sizes to continue!',
    Yes: 'Yes',
    No: 'No',
    PriceOnSelection: 'Price on selection',
    SpeifyQty: 'You should specify the quantity you need to add to your cart',
    SeeMore: 'see more...',
    NoSearchResults: 'Oops! No results match with your search',
    EmptyEishlist: "You didn't have added any items to your wishlist!",
    Branches: 'Branches',
    Confirm: 'Confirm',
    CheckoutConfirm: 'Are you sure you want to place youre order ?',
    PlaceOrder: 'Place my order',
    AddressSavedSuccessfully: 'Address saved successfully',
    ConfirmDeleteAddress: 'Are you sure you want to delete {0}?',
    DeletedSuccessfully: 'Deleted successfully',
    PlacedSuccessfully: 'Your order placed successfully!',
    NoOrders: "You don't have any previous orders yet!",
    SelectAddress: 'Select delivery address',
    SelectAddAddress: 'Select delivery address or add new',
    Coverage: 'Coverage',
    KG: 'KG',
    EstimatePerCoat: 'Estimated Coverage for 2 coat (optimal coat)',
    SQ: 'sq/m2',
    M2: 'm2',
    SuggestedSize: 'The suggested optimal size',
    Piece: 'Piece',
    HowMuchNeedTip:
      'This calculator tells you how much paint you’ll need for two coats for the most professional-looking finish. This is intended for estimation purposes only. Paint estimator results and coverage per gallon may vary depending on factors like wall texture, color choice, or surface condition.',
    DimensionsTip: 'Add each surface area you’re painting i.e. wall',
    DoorsTip:
      'This takes a standard deduction based on average sized windows and doors.',
    LearnMoreTitle: 'How much materials do you need for perfect coverage?',
    LearnMoreP1: `Now, you’re probably wondering how much materials and paint to buy. First, you’ll need to understand materials and paint coverage so that you can get your material estimate right.\nEvery room has its own quirks that impact how much material will cover. Things like the condition, texture, and porosity of your wall surface can make a difference in how much material or paint the walls will soak up. Below are the general material coverage guidelines to follow, assuming your walls are in good condition, plus some things to keep in mind in those quirky edge cases.`,
    TransactionFailed: 'Seems like you are have a trouble with your payment!',
    ConfirmCancelPayment: 'Are you sure you want to cancel tha payment ?',
    ShowAll: 'Show all...',
    SeeLess: 'See less...',
    SuggestedForYou: 'Suggested for you...',
    Min: 'min',
    Max: 'max',
    NoNotifications: 'you dont have any notification yet!',
    LoadingQuestions: 'Loading questions...',
    OutOfStock: 'Out of stock!',
    Skip: 'Skip',
    AddAnyWay: 'Add anyway',
    PermissionRequired:
      'External storage permission required in order to download!',
    QuestionsDescription:
      'For more information about the steps and stages that precede the application of the material, please check the following',
    Attachment: 'Attachment {0}',
    English: 'English',
    Arabic: 'العربية',
    ConfirmLang: 'تاكيد',
    ChangeLangConfirm: 'يتطلب تغيير اللغة اعادة تحميل التطبيق، متابعة ؟',
    YesLang: 'نعم',
    NoLang: 'لا',
    langDirection: 'ltr',
    SendCode: 'Send code',
    UserNotFound: 'User not found!',
    EnterValidCode: 'Enter valid code!',
    Verify: 'Verify',
    VerifyAccount: 'Verify your account',
    EnterOTP: 'Enter code we sent for you to continue',
    IncorrectPhone: 'Incorrect phone',
    ByEmail: 'by email',
    ByPhone: 'by phone',
    EnterValidPhone: 'Enter valid phone number',
    NewPassSent:
      'We sent you a new password, login and chage your password from settings',
    InvalidCode: 'Invalid code! please try again',
    Resend: 'Resend code',
    CodeSent: 'Code sent successfully',
    NeedCustomerSupport:
      'You have an items need customer support! we will contact you as soon as possible',
    TypeCodeHere: 'Type the code we sent for you here',
    DeliveryFees: 'Delivery fees',
    FillInfo: 'Please fill all info!',
    SaveAddress: 'Save address',
    SelectCity: 'Select city',
    SelectArea: 'Select area',
    LocationSelected: 'Location selected',
    PhonePlaceholder: 'Phone (07xxxxxxxx)',
    Colors: 'Colors',
    TryIt: 'Try it',
    ViewIt: 'View',
    Tinting: 'Tinting',
    SelectPaymentAddress:
      'Select payment option and delivery address in order to continue',
    TintingDesc:
      'Tinting\nChoose it and complete the order and you will be contact to technical support to choose your favorite color from the colors that contain the wonderful colors',
    Search: 'Search',
    ExitApp: 'Exit app',
    ExitAppConfirm: 'Are you sure you want to exit the app?',
    BestSelling: 'Best selling',
    SelectSize: 'Select size',
    Close: 'Close',
    Description: 'Description',
    Video: 'Video',
    SuggestedColors: 'Suggested colors',
    NoSuggestions: 'There is no suggestions found...',
    All: 'All',
    Count: 'Piece',
    Location: 'Location',
    LocationDesc: 'Do you want to get your location automatically?',
    Specs: 'Specifications',
    PriceSupport: 'We will contact you on pricing upon request.',
    DownloadedSuccesffully: 'Downloaded successfully!',
    Thickness: 'Thickness Layer:',
    Attachments: 'Attachments',
    From: 'From',
    To: 'To',
    Apple: 'Sign in with Apple',
    Facebook: 'Sign in with Facebook',
    Google: 'Sign in with Google',
    Wallpaper: 'Wall paper',
    EnterUsername: 'Enter a username to continue',
    EmailPhone: 'Phone number or Email',
    FullnamePH: 'Full name (ex. Ahmad Ali)',
    FullNameIncorrect: 'Please enter the full name (eg. Ahmad Ali)',
    COD: 'Cash on delivery',
    Credit: 'Credit/Debit cards',
    Zain: 'Zain cash',
    Paypal: 'Paypal',
    NeedPhone:
      'Enter your phone number please in order to continue and complete your order',
    LocationPermission:
      'Location permission required in order to get your location, do you want to enable it from settings ?',
    OpenSettings: 'open settings',
    UserType: 'User type',
    SelectUserType: 'Select user type',
    Whatsapp: 'Whatsapp',
  },
  ar: {
    // to be translated later
    LangID: '2',
    Tiler: 'بليط',
    Painter: 'دهين',
    User: 'مستخدم',
    DiscoverBestSelling: 'استكشف \nالاكثر مبيعا',
    VirtualRoom: 'الغرفة الافتراضية',
    PaintOnline: 'قم بتلوين غرفتك اونلاين باستخدام ميزة الغرفة الافتراضية',
    TechnicalExcellence: 'التميز التقني',
    TakeTour: 'قم بجولة',
    OurProducts: 'منتجاتنا',
    AllProducts: 'عرض المزيد',
    Filter: 'تصنيف',
    Home: 'الرئيسية',
    Products: 'منتجات',
    MyOrders: 'طلباتي',
    MyWishList: 'المفضلة',
    Gallery: 'الاستوديو',
    Videos: 'فيديوهات',
    Articles: 'مقالات',
    Offers: 'عروض',
    ContactUS: 'تواصل معنا',
    Login: 'تسجيل الدخول',
    Logout: 'تسجيل الخروج',
    SalesTerms: 'شروط البيع',
    TermsNConditions: 'الشروط والأحكام',
    PrivacyPolicy: 'سياسة الخصوصية',
    FindColor: 'ابحث عن المنتج',
    ProdectsOffers: 'منتجات العروض الخاصه',
    ATOZ: 'أ-ي',
    ZTOA: 'ي-أ',
    Color: 'اللون',
    LowToHigh: 'الأقل للأعلى',
    HighToLow: 'الأعلى للأقل',
    Price: 'السعر',
    Date: 'التاريخ',
    Place: 'المكان',
    Keywords: 'كلمات مفتاحية',
    SearchPlaceholder: 'مثال. مات',
    TDS: 'TDS',
    MSDS: 'MSDS',
    Certificate: 'شهادة',
    AddToCart: 'اضف للسلة',
    AddToWishlist: 'اضف للمفضلة',
    RemoveWishlist: 'ازالة مفضلة',
    PaintCalculator: 'حاسبة المواد',
    PaintCalculatorTitle: 'حاسبة استهلاك المواد',
    BookCall: 'احجز مكالمة',
    RequestAgent: 'اطلب وكيل',
    RelatedItems: 'منتجات ذات صلة',
    Download: 'تنزيل',
    PickDateTime: 'اختر التاريخ والوقت',
    Time: 'الوقت',
    Submit: 'موافق',
    Email: 'البريد الالكتروني',
    Password: 'كلمة المرور',
    Failed: 'فشل',
    Success: 'نجاح',
    OR: 'او',
    ForgotPass: 'نسيت كلمة المرور؟',
    CreateAccount: 'انشاء حساب جديد؟',
    EnterEmailToSendCode:
      'ادخل بريدك الالكتروني/رقم هاتفك لارسال كلمة مرور جديدة اليك',
    EnterEmail: 'حقل البريد الاكتروني مطلوب!',
    EnterPassword: 'حقل كلمة المرور مطلوب!',
    EnterValidEmail: 'ادخل بريد الكتروني صالح!',
    PasswordTooShort: 'كلمة المرور قصيرة!',
    EmailPassIncorrect:
      'البريد الالكتروني او كلمة المرور غير صحيحة! تحقق من بيانات الدخول الخاصة بك وحاول مرة أخرى',
    UserLoggedIn: 'تم تسجيل الدخول بنجاح!',
    Register: 'التسجيل',
    HaveAccount: 'لديك حساب؟ سجل الدخول',
    Fullname: 'الاسم الكامل',
    Phone: 'رقم الهاتف',
    ConfirmPassword: 'تاكيد كلمة المرور',
    AgreeStatements: 'أوافق على جميع البيانات الواردة في',
    TermsOfService: 'شروط الخدمة!',
    TermsOfSales: 'شروط البيع!',
    EnterFullName: 'حقل الاسم الكامل مطلوب!',
    FullnameTooShort: 'الاسم الكامل قصير!',
    EnterPhone: 'حقل رقم الهاتف مطلوب!',
    PhoneTooShort: 'رقم الهاتف قصير!',
    PassDontMatch: 'كلمة المرور غير مطابقة!',
    EnterConfirmPassword: 'حقل تاكيد كلمة المرور مطلوب!',
    EmailAlreadyTaken:
      'عذرا! يوجد بالفعل حساب يستخدم هذا البريد الإلكتروني. حاول تسجيل الدخول أو استخدام بريد إلكتروني آخر.',
    UserRegisterdSucessfully: 'تم تسجيل المستخدم بنجاح!',
    Required: 'مطلوب',
    UserAgreeRequired:
      'يجب أن توافق على شروط الخدمة وشروط البيع من أجل استخدام خدماتنا.',
    LearnMore: 'اعرف المزيد',
    Item: 'المنتج',
    Delete: 'حذف',
    WishList: 'المفضلة',
    VideoGallery: 'معرض\nالفيديو',
    SwitchToPhoto: 'قم بالتبديل إلى معرض الصور',
    Veiws: 'مشاهدة',
    PhotoGallery: 'معرض الصور',
    SwitchToVideo: 'قم بالتبديل إلى معرض الفيديو',
    Blog: 'مقالات',
    LearnAboutPaint: 'تعرف على الطلاء المفضل لديك',
    YourCart: 'عربةالتسوق',
    Checkout: 'الدفع',
    TrackYOrder: 'تتبع طلبك',
    JOD: 'د.أ',
    ContinueShopping: 'متابعة التسوق',
    ContactInfo: 'معلومات التواصل',
    ShippingAddress: 'عنوان التوصيل',
    FirstName: 'الاسم الاول',
    LastName: 'الاسم الاخير',
    Address: 'العنوان',
    Apartment: 'الشقة',
    OrderPlaced: 'تم اتمام الطلب بنجاح',
    ProcessOrder: 'تجهيز الطلب',
    ShippingOrder: 'توصيل الطلب',
    OrderDelivered: 'تسليم الطلب',
    HappyToHelp: 'يسعدنا الرد على الأسئلة أو مساعدتك في العودة',
    DistrebutionPoints: 'نقاط البيع',
    ClickLocation: 'انقر على الموقع لعرضه',
    VisitFactory: 'قم بزيارة المصنع',
    MyProfile: 'حسابي',
    Hello: 'مرحبا',
    EditProfile: 'تعديل حسابي',
    MyInfo: 'معلوماتي',
    MyPassword: 'كلمة المرور',
    MyAddresses: 'عناويني',
    Sale: '%  تخفيضات',
    Question: 'س',
    Next: 'التالي',
    Back: 'السابق',
    PinYourLocation: 'حدد موقعك ...',
    ProfileUpdatedSuccess: 'تم تحديث الملف الشخصي بنجاح!',
    TakeSurvey: 'قم باستطلاع',
    EditPassword: 'تعديل كلمة المرور',
    PasswordChangedSuccess: 'تم تعديل كلمة المرور بنجاح!',
    OrderNo: 'طلب رقم.',
    OrderDate: 'تاريخ الطلب',
    Total: 'المجموع',
    MoreDetails: 'المزيد من التفاصيل',
    AddNewAddress: 'اضافة عنوان جديد',
    AddressName: 'اسم العنوان',
    AddressNameTooShort: 'اسم العنوان قصير جدا',
    Notifications: 'الاشعارات',
    UseCamera: 'الكاميرا',
    UseGallery: 'الاستوديو',
    Quantity: 'الكمية',
    HowMuchPaint: 'كم أحتاج من الطلاء؟',
    NoNeedCrunch: `لا حاجة لتخمين الكميات  لدينا آلة حاسبة يدوية لحساب الكمية المطلوبة عند استخدام مواد وطلاءات شركة القدس.\nإبدأ ، أدخل أبعاد السطح (الأسطح) اللتي تود تطبيق المواد عليها.الابعاد (بالمتر ). يفترض مقدر المواد الخاص بنا أن تطبيق المواد والطلاء للحصول على تغطية مثالية.`,
    EnterDimensions: 'أدخل أبعاد كل سطح لحساب مساحته',
    CustomFeild: 'اختر قيمك',
    Area: 'المساحة',
    Width: 'العرض',
    Height: 'الطول',
    AddWall: 'اضافة حائط',
    SubtractWindowsDoors: 'انقص النوافذ والأبواب من الحساب',
    Window: 'نافذة',
    Door: 'باب',
    HowMuchNeeded: 'كم تحتاج لتغطية {0} م2',
    HowMuch2Coats: 'كم تحتاج لنغطية طبقتين',
    Paint: 'طلاء',
    Galons: 'جالونات',
    Primer: 'بريمير',
    UserExists: 'يوجد مستخدم بهذه المعلومات بالفعل!',
    Oops: 'عذراً! حدث خطأ ما. أعد المحاولة من فضلك.',
    NotSupported: 'جهازك لايدعم تطبيقات الخرائط!',
    WhatsappNotSupported: 'لا يوجد تطبيق واتساب على جهازك',
    PhoneIsUsed: 'رقم الهاتف هذا مستعمل!',
    RemovedSuccessfully: 'تمت إزالة العنصر بنجاح!',
    AddedSuccessfully: 'تمت إضافة العنصر بنجاح!',
    SelectDay: 'حدد اليوم المفضل للمكالمة للمتابعة!',
    SelectTime: 'حدد وقت الاتصال المفضل للمتابعة!',
    BookedSuccesfully:
      'تم حجز المكالمة بنجاح! سيتصل بك فريقنا في الوقت المحدد.',
    OnlyAvailableStock: 'لا يمكنك إضافة أكثر من {0} في الوقت الحالي.',
    CheckCode: 'التحقق من الرمز',
    IncorrectCode: 'رمز خاطئ!',
    EnterCode: 'ادخل الرمز للمتابعة!',
    TypeHere: 'اكتب هنا ...',
    YourCartIsEmpty: 'عربة التسوق فارغة',
    Size: 'الحجم',
    ShouldSelectColor: 'يجب عليك اختيار أحد الألوان للمتابعة!',
    ShouldSelectSize: 'يجب عليك تحديد أحد الأحجام للمتابعة!',
    Yes: 'نعم',
    No: 'لا',
    PriceOnSelection: 'السعر حسب الاختيار',
    SpeifyQty:
      'يجب عليك تحديد الكمية التي تريد إضافتها إلى سلة التسوق الخاصة بك',
    SeeMore: 'المزيد...',
    NoSearchResults: 'عذراً! لا توجد نتائج تطابق بحثك',
    EmptyEishlist: 'لم تقم بإضافة أي عناصر إلى قائمة الرغبات الخاصة بك!',
    Branches: 'نقاط البيع',
    Confirm: 'تاكيد',
    CheckoutConfirm: 'هل أنت متأكد أنك تريد أن تتم طلبك ؟',
    PlaceOrder: 'اتمام الطلب',
    AddressSavedSuccessfully: 'تم حفظ العنوان بنجاح',
    ConfirmDeleteAddress: 'هل أنت متأكد أنك تريد حذف {0}؟',
    DeletedSuccessfully: 'حذف بنجاح',
    PlacedSuccessfully: 'تم اتمام طلبك بنجاح!',
    NoOrders: 'ليس لديك أي طلبات سابقة حتى الآن!',
    SelectAddress: 'حدد عنوان التوصيل',
    SelectAddAddress: 'حدد عنوان التوصيل او اضف عنوان جديد',
    Coverage: 'تغطية',
    KG: 'كغ',
    EstimatePerCoat: 'التغطية المقدرة هي تغطية مثالية (2طبقة)',
    SQ: 'متر مربع/م2',
    M2: 'م2',
    SuggestedSize: 'الحجم الأمثل المقترح',
    Piece: 'قطعة',
    HowMuchNeedTip: `تخبرك هذه الآلة الحاسبة بكمية المواد والطلاء التي ستحتاجها للحصول على مظهر نهائي مثالي . هذا مخصص لأغراض التقدير فقط. قد تختلف نتائج مقدر الطلاء والتغطية لكل كجم اعتمادًا على عوامل مختلفة مثل طبيعة الجدار أو اختيار اللون أو حالة السطح.`,
    DimensionsTip: 'اضف مساحة كل سطح تود طلائه',
    DoorsTip:
      'يتطلب هذا خصمًا قياسيًا بناءً على النوافذ والأبواب ذات الحجم المتوسط.',
    LearnMoreTitle: 'ما هي كمية المواد التي تحتاجها لتغطية مثالية؟',
    LearnMoreP1: `ربما تتساءل عن كمية الطلاء والمواد التي يجب شراؤها.\nأولاً ، ستحتاج إلى فهم تغطية الطلاء والمواد حتى تتمكن من الحصول على التقدير الخاص بك بشكل صحيح.\n\nكل سطح وله مواصفاته التي تؤثر على مقدار وكمية المواد المطلوبه. ويمكن لحالة وملمس ومسامية سطح الحائط والحواف الملتويه ان وجدت فيه أن تحدث فرقًا في مقدار المواد والطلاء الذي ستمتصه الجدران. لذلك يجب وضع هذه التفاصيل بعين الاعتبار \n\nىحيث تقوم الاله الحاسبة بإحتساب كمية المواد للأسطج المطلوبة عندما تكون في الحالة مثالية .`,
    TransactionFailed: 'يبدو أنك تواجه مشكلة في الدفع!',
    ConfirmCancelPayment: 'هل أنت متأكد أنك تريد إلغاء الدفع ؟',
    ShowAll: 'عرض الكل...',
    SeeLess: 'عرض اقل...',
    SuggestedForYou: 'منتجات مقترحة...',
    Min: 'ادنى',
    Max: 'اقصى',
    NoNotifications: 'ليس لديك اشعارات جديدة حتى الآن!',
    LoadingQuestions: 'جاري تحميل الاسئلة...',
    OutOfStock: 'غير متوفر!',
    Skip: 'تخطي',
    AddAnyWay: 'أضف على أي حال',
    PermissionRequired: 'مطلوب إذن الوصول للتخزين خارجي من أجل التنزيل!',
    QuestionsDescription:
      'لمزيد من المعلومات حول الخطوات والمراحل التي تسبق تطبيق المادة ، يرجى التحقق مما يلي',
    Attachment: 'مرفق {0}',
    English: 'English',
    Arabic: 'العربية',
    ConfirmLang: 'Confirm',
    ChangeLangConfirm: 'Change language requires app reload, continue ?',
    YesLang: 'Yes',
    NoLang: 'No',
    langDirection: 'rtl',
    SendCode: 'ارسل الرمز',
    UserNotFound: 'المستخدم غير موجود',
    EnterValidCode: 'ادخل رمز صحيح للاستمرار!',
    Verify: 'تاكيد',
    VerifyAccount: 'وثق حسابك',
    EnterOTP: 'ادخل الرمز الذي ارسل اليك للاستمرار',
    IncorrectPhone: 'رقم الهاتف خاطئ',
    ByEmail: 'بريد الكتروني',
    ByPhone: 'رقم الهاتف',
    EnterValidPhone: 'ادخل رقم هاتف صحيح',
    NewPassSent:
      'لقد أرسلنا لك كلمة مرور جديدة ، قم بتسجيل الدخول وتغيير كلمة المرور الخاصة بك من الإعدادات',
    InvalidCode: 'الرمز خاطئ! يرجى التاكد من الرمز',
    Resend: 'أعد إرسال الرمز',
    CodeSent: 'تم إرسال الرمز بنجاح',
    NeedCustomerSupport:
      'لديك عناصر تحتاج إلى الدعم الفني! سنتواصل معك بأقرب وقت ممكن',
    TypeCodeHere: 'اكتب الرمز الذي أرسلناه لك هنا',
    DeliveryFees: 'اجور التوصيل',
    FillInfo: 'يرجى تعبئة جميع المعلومات!',
    SaveAddress: 'حفظ العنوان',
    SelectCity: 'اختر المدينة',
    SelectArea: 'اختر المنطقة',
    LocationSelected: 'تم تحديد الموقع',
    PhonePlaceholder: '(07xxxxxxx) رقم الهاتف',
    Colors: 'الألوان',
    TryIt: 'جربه',
    ViewIt: 'عرض',
    Tinting: 'قابل للتلوين',
    SelectPaymentAddress: 'اختر طريقة الدفع وعنوان التوصيل للاستمرار',
    TintingDesc:
      'قابل للتلوين\nاخترها وقم بأكمال الطلب وسيتم تحويلك الى الدعم الفني لتختار لونك المفضل من مروحة الألوان التي تحتوي على العديد من الألوان الرائعة',
    Search: 'بحث',
    ExitApp: 'الخروج',
    ExitAppConfirm: 'هل انت متاكد انك تريد الخروج من التطبيق؟',
    BestSelling: 'الاكثر مبيعاً',
    SelectSize: 'اختر الحجم',
    Close: 'اغلاق',
    Description: 'وصف المنتج',
    Video: 'فيديو',
    SuggestedColors: 'الوان مقترحة...',
    NoSuggestions: 'لا يوجد مقترحات...',
    All: 'الكل',
    Count: 'عدد',
    Location: 'الموقع',
    LocationDesc: 'هل تود تحديد موقعك تلقائياً ؟',
    Specs: 'خصائص المنتج',
    PriceSupport: 'سنقوم بالتواصل معك لتحديد السعر عند الطلب',
    DownloadedSuccesffully: 'تم التنزيل بنجاح!',
    Thickness: 'سمك الطبقة:',
    Attachments: 'مرفقات',
    From: 'من',
    To: 'الى',
    Apple: 'متابعة باستخدام ابل',
    Facebook: 'متابعة باستخدام فيسبوك',
    Google: 'متابعة باستخدام جوجل',
    Wallpaper: 'ورق الجدران',
    EnterUsername: 'ادخل رقم الهاتف او البريد الالكتروني للمتابعه',
    EmailPhone: 'رقم الهاتف او البريد الالكتروني',
    FullnamePH: 'الاسم الكامل (مثال: احمد علي)',
    FullNameIncorrect: 'يرجى ادخال الاسم الكامل (مثال: احمد علي)',
    COD: 'الدفع عند التوصيل',
    Credit: 'بطاقات ائتمانية',
    Zain: 'زين كاش',
    Paypal: 'بايبال',
    NeedPhone: 'يرجى ادخال رقم هاتفك للمتابعة واتمام طلبك',
    LocationPermission:
      'اذن الوصول للموقع مطلوب لنتمكن من معرفة موقعك، هل تريد تفعيل الموقع من الاعدادات ؟',
    OpenSettings: 'الذهاب للاعدادات',
    UserType: 'نوع المستخدم',
    SelectUserType: 'أختر نوع المستخدم',
    Whatsapp: 'واتساب',
  },
});
