const SAVE_USER = 'SAVE_USER';
const CLEAR_USER = 'CLEAR_USER';
const ADD_CART_ITEM_PENDING = 'ADD_CART_ITEM_PENDING';
const ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS';
const ADD_CART_ITEM_FAILED = 'ADD_CART_ITEM_FAILED';
const GET_CART_PENDING = 'GET_CART_PENDING';
const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
const GET_CART_FAILED = 'GET_CART_FAILED';
const DELETE_CART_ITEM_PENDING = 'DELETE_CART_ITEM_PENDING';
const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS';
const DELETE_CART_ITEM_FAILED = 'DELETE_CART_ITEM_FAILED';
const SAVE_USER_WISHLIST = 'SAVE_USER_WISHLIST';
const CLEAR_CART = 'CLEAR_CART';

const actions = {
  SAVE_USER,
  CLEAR_USER,
  ADD_CART_ITEM_PENDING,
  ADD_CART_ITEM_SUCCESS,
  ADD_CART_ITEM_FAILED,
  GET_CART_PENDING,
  GET_CART_SUCCESS,
  GET_CART_FAILED,
  DELETE_CART_ITEM_PENDING,
  DELETE_CART_ITEM_SUCCESS,
  DELETE_CART_ITEM_FAILED,
  SAVE_USER_WISHLIST,
  CLEAR_CART,
};
export default actions;
